/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_securemessaging_SecureCrypto */

#ifndef _Included_com_securemessaging_SecureCrypto
#define _Included_com_securemessaging_SecureCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_securemessaging_SecureCrypto
 * Method:    testConnection
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_securemessaging_SecureCrypto_testConnection
  (JNIEnv *, jobject);

/*
 * Class:     com_securemessaging_SecureCrypto
 * Method:    encryptMessage
 * Signature: (Ljava/lang/String;Z)Lcom/securemessaging/EncryptionResult;
 */
JNIEXPORT jobject JNICALL Java_com_securemessaging_SecureCrypto_encryptMessage
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_securemessaging_SecureCrypto
 * Method:    decryptMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_securemessaging_SecureCrypto_decryptMessage
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_securemessaging_SecureCrypto
 * Method:    isValidKey
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_securemessaging_SecureCrypto_isValidKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_securemessaging_SecureCrypto
 * Method:    getSystemInfo
 * Signature: ()Lcom/securemessaging/SystemInfo;
 */
JNIEXPORT jobject JNICALL Java_com_securemessaging_SecureCrypto_getSystemInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
